import globalStyles from "./globals.module.scss";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={globalStyles.platinum}>{children}</body>
        </html>
    );
}
